{ config, lib, inputs, pkgs, systemSettings, userSettings, ... }:

{
  imports =
    [
      ./hardware-configuration.nix
      ./system/boot.nix
      ./system/gpu.nix
      ./system/network.nix
    ];

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      # Garbage collection
      auto-optimise-store = true;
      # Cachix
      substituters = ["https://hyprland.cachix.org"];
      trusted-public-keys = ["hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="];
    };
    # Garbage collection
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
  };

  xdg = {
    portal = {
      enable = true;
      wlr.enable = true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-wlr
      ];
    };
  };

  nixpkgs = {
    config = {
      allowUnfree = true;
    };
  };

  environment = {
    variables = {
      XDG_CONFIG_HOME = "${builtins.getEnv "HOME"}/.dotfiles";
    };
    sessionVariables = {
      NIXOS_OZONE_WL = "1";
    };
  };

  services = {
    greetd = {
      enable = true;
      settings = {
        default_session = {
          # Wayland Desktop Manager is installed only for user ryan via home-manager!
          user = userSettings.username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
          # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
        };
      };
    };
    openssh = {
      enable = true;
    };
  };

  programs = {
    hyprland = {
      enable = true;
      package = inputs.hyprland.packages."${pkgs.system}".hyprland;
    };
    # Enable laptop brightness keys
    light = {
      enable = true;
    };
    zsh = {
      enable = true;
    };
  };

  time.timeZone = systemSettings.timezone;
  
  users.users.${userSettings.username} = {
    description = "Fredrik";
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "libvirtd" "video" ];
    shell = pkgs.zsh;
    packages = with pkgs; [
    ];
  };

  system.stateVersion = "23.11"; # Did you read the comment?

}